name: FastAPI CI

on:
  push:
    paths:
      - 'backend/**'     # 仅当 backend 目录变更时触发

jobs:
  fastapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run FastAPI (Uvicorn)
        working-directory: backend
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &

      # 可选：运行测试
      - name: Run tests
        working-directory: backend
        run: |
          pytest || echo "No tests yet"
